config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  resources :items do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  validates :memo, presence: true
  belongs_to :user
  has_many :comments

  def self.search(search)
    if search != ""
      Item.where('memo LIKE(?)', "%#{search}%")
    else
      Item.all
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :img, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items
  has_many :comments

  validates :nickname, presence: true, length: { maximum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/items/#{comment.item.id}"
  end

  private 
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, item_id: params[:item_id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_item, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @items = Item.includes(:user).order("created_at DESC")
  end

  def new
    @item = Item.new
  end

  def create
    Item.create(item_params)
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
  end

  def edit
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
  end

  def show
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
  end

  def search
    @items = Item.search(params[:keyword])
  end

  private
  def item_params
    params.require(:item).permit(:image, :memo).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @items = user.items
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.haml
= form_with(model: item, local: true) do |form|
  = form.text_field :image, placeholder: "Image Url"
  = form.text_area :memo, pleaceholder: "memo", rows: "10"
  = form.submit "SEND"

= form_for @post do |f|
  = f.file_field :img
  = f.submit 'アップロードする'

app/views/items/_item.html.haml
.content_post{:style => "background-image: url(#{item.image});"}
  .more
    %span
      = image_tag 'arrow_top.png'
    %ul.more_list
      %li
        =link_to '詳細', item_path(item.id), method: :get
      - if user_signed_in? && current_user.id == item.user_id
        %li
          =link_to  '編集', edit_item_path(item.id), method: :get
        %li
          = link_to '削除', item_path(item.id), method: :delete
  %p= item.memo
  %span.name
    %a{:href =>"/users/#{item.user.id}"}
      %span 投稿者
      = item.user.nickname

app/views/items/create.html.haml
.contents.row
  .success
    %h3 投稿が完了しました
    %a.btn{:href => "/"} 投稿一覧へ戻る

app/views/items/destroy.html.haml
.contents.row
  .success
    %h3 削除が完了しました
    %a.btn{:href => "/"} 投稿一覧へ戻る

app/views/items/edit.html.haml
.contents.row
  .container
    %h3 編集する
    = render partial: "form", locals: { item: @item}

app/views/items/index.html.haml
= form_with(url: search_items_path, local: true, method: :get, class: "search-form") do |form|
  = form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input"
  = form.submit "検索", class: "search-btn"
.contents.row
  - @items.each do |item|
    = render partial: "item", locals: { item: item }
    

app/views/items/new.html.haml
.contents.row
  .container
    %h3 投稿する
    = render partial: "form", locals: { item: @item}

app/views/items/search.html.haml
= form_with(url: search_items_path, local: true, method: :get, class: "search-form") do |form|
  = form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input"
  = form.submit "検索", class: "search-btn"
.contents.row
  - @items.each do |item|
    = render partial: "item", locals: {item: item}

app/views/items/show.html.haml
.contents.row
  .content_post{ :style => "background_image: url(#{@item.image});"}
    - if user_signed_in? && current_user.id == @item.user_id
      .more
        %span= image_tag'arrow_top.png'
        %ul.more_list
          %li
            =link_to '編集',  edit_item_path(@item.id), method: :get
          %li
            =link_to '削除',  item_path(@item.id), method: :delete
    %p= @item.memo
    %a{:href =>"/users/#{@item.user.id}"}
      %span 投稿者
      = @item.user.nickname
  .container
    - if user_signed_in?
      = form_with(model: [@item, @comment], local: true) do |form|
        = form.text_area :text, placeholder: "コメントする", rows: "2"
        = form.submit "SEND"
    - else
      %strong
        %p ※※※ コメントの投稿には新規登録/ログインが必要です ※※※
    .comments
      %h4<コメント一覧>
      - if @comments
        - @comments.each do |comment|
          %p
            %strong
              = link_to comment.user.nickname, "/users/#{comment.user_id}"
            = comment.text

app/views/items/update.html.haml
.contents.row
  .success
    %h3 更新が完了しました
    %a.btn{:href => "/"} 投稿一覧へ戻る

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FassionShareApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header.header
      .header__bar.row
        %h1.grid-6
          %a{:href => "/"}Fassion_share_top
        - if user_signed_in?
          .user_nav.grid-6
            %span
              = current_user.nickname
              %ul.user__info
                %li
                  = link_to "マイページ", "/users/#{current_user.id}"
                  = link_to "ログアウト", destroy_user_session_path, method: :delete
            = link_to "投稿する", new_item_path, class: "post" 
        - else
          .grid-6
            = link_to "ログイン", new_user_session_path, class: "post"
            = link_to "新規登録", new_user_registration_path, class: "post"
    = render 'layouts/notifications'
    = yield
    %footer
      %p
        Producer: tsuyoshi ueda.

app/views/users/show.html.haml
.contents.row
  %p
  = @nickname
  さんの投稿一覧
  - @items.each do |item|
    = render partial: "items/item", locals: {item: item}